// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react"

interface Repo {
  countStars: number
  repo: string
}

interface UserApiResponse {
  repos: Repo[]
  nickname: string
}

// Define a service using a base URL and expected endpoints
export const githubApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://api.github.com/users" }),
  reducerPath: "usersApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Users", "Repos"],
  endpoints: build => ({
   //Supply generics for the return type (in this case `QuotesApiResponse`)
    //and the expected query argument. If there is no argument, use `void`
    //for the argument type instead.
    getUsers: build.query<UserApiResponse, number>({
      query: (nickname) => `users/${nickname}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "Users", id }],
    }),
    getRepos: build.query<Repo[], number>({
      query: (repo) => `repos/${repo}`,
      providesTags: (result, error, id) => [{ type: "Repos", id }],
    })
  }),
})

// Hooks are auto-generated by RTK-Query
// Same as `quotesApiSlice.endpoints.getQuotes.useQuery`
export const { useGetUsersQuery, useGetReposQuery } = githubApiSlice
